### ISSUE TITLE
Bug in Multi-Class Classification?

### ISSUE THREAD

**Issue by gwohlgen** [jfilter/text-classification-keras#10]
Hi,

we tried text-classification-keras, I works really nicely with single classes.

Today I tried it on a dataset with multiple classes per document, and ran into an error which I couldn't fix.

```
python eswc_eurlex.py train
Using TensorFlow backend.
INFO:texcla.embeddings:Building embeddings index...
INFO:texcla.embeddings:Done
number of classes: 1
19314 76406184
INFO:texcla.embeddings:Loading embeddings for all words in the corpus
2018-12-05 19:07:36.743116: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-05 19:07:36.755305: W tensorflow/core/framework/allocator.cc:113] Allocation of 37423200 exceeds 10% of system memory.
2018-12-05 19:07:36.829602: W tensorflow/core/framework/allocator.cc:113] Allocation of 37423200 exceeds 10% of system memory.
2018-12-05 19:07:36.845069: W tensorflow/core/framework/allocator.cc:113] Allocation of 37423200 exceeds 10% of system memory.
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 200)          0                                            
__________________________________________________________________________________________________
embedding_1 (Embedding)         (None, 200, 300)     9355800     input_1[0][0]                    
__________________________________________________________________________________________________
conv1d_1 (Conv1D)               (None, 198, 64)      57664       embedding_1[0][0]                
__________________________________________________________________________________________________
conv1d_2 (Conv1D)               (None, 197, 64)      76864       embedding_1[0][0]                
__________________________________________________________________________________________________
conv1d_3 (Conv1D)               (None, 196, 64)      96064       embedding_1[0][0]                
__________________________________________________________________________________________________
global_max_pooling1d_1 (GlobalM (None, 64)           0           conv1d_1[0][0]                   
__________________________________________________________________________________________________
global_max_pooling1d_2 (GlobalM (None, 64)           0           conv1d_2[0][0]                   
__________________________________________________________________________________________________
global_max_pooling1d_3 (GlobalM (None, 64)           0           conv1d_3[0][0]                   
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 192)          0           global_max_pooling1d_1[0][0]     
                                                                 global_max_pooling1d_2[0][0]     
                                                                 global_max_pooling1d_3[0][0]     
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 192)          0           concatenate_1[0][0]              
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 1)            193         dropout_1[0][0]                  
==================================================================================================
Total params: 9,586,585
Trainable params: 230,785
Non-trainable params: 9,355,800
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "eswc_eurlex.py", line 110, in <module>
    train()
  File "eswc_eurlex.py", line 102, in train
    experiment.train(x=ds.X, y=ds.y, validation_split=0.1, model=model, word_encoder_model=word_encoder_model, shuffle=True) # wohlg added shuffle
  File "/home/wohlg/anaconda3/lib/python3.6/site-packages/texcla/experiment.py", line 76, in train
    batch_size=batch_size, callbacks=create_callbacks(exp_path, patience), **fit_args)
  File "/home/wohlg/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 950, in fit
    batch_size=batch_size)
  File "/home/wohlg/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 802, in _standardize_user_data
    check_array_length_consistency(x, y, sample_weights)
  File "/home/wohlg/anaconda3/lib/python3.6/site-packages/keras/engine/training_utils.py", line 236, in check_array_length_consistency
    'and ' + str(list(set_y)[0]) + ' target samples.')
ValueError: Input arrays should have the same number of samples as target arrays. Found 19314 input samples and 76406184 target samples.
```

I tracked the issue down into class `Dataset`.
We have 19314 documents as input, which have 3956 distinct labels. Per document it's about 5 labels on average. In line 34/35 of `https://github.com/jfilter/text-classification-keras/blob/master/texcla/data.py` the MultiLabelBinarizer seems to create a matrix of size 19314 * 3956 = 76406184 for `y`, this also correspond with the message in the exception.

What is needed to make the Keras understand that `len(y)=num_docs * num_classes` in the multilabel case, and not just `num_docs`?

I'd be very grateful for help,
Best, Gerhard

**Comment by jfilter** [comment]
Fixed in https://github.com/jfilter/text-classification-keras/commit/6dd3937c7fe3437761a9a0700d817f009386e530
