### ISSUE TITLE
https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.simple.vec: 403 -- Forbidden

### ISSUE THREAD

**Issue by chenqing** [jfilter/text-classification-keras#11]
Traceback (most recent call last):
  File "imdb.py", line 55, in <module>
    train()
  File "imdb.py", line 34, in train
    ds_train.num_classes, ds_train.tokenizer.token_index, max_tokens=MAX_LEN, embedding_type='fasttext.wiki.simple', embedding_dims=300)
  File "/home/chenqing/anaconda3/lib/python3.7/site-packages/texcla/models/token_model.py", line 32, in __init__
    embedding_type, embedding_dims, embedding_path)
  File "/home/chenqing/anaconda3/lib/python3.7/site-packages/texcla/embeddings.py", line 236, in get_embeddings_index
    embedding_type_obj['file'], origin=embedding_type_obj['url'], extract=extract, cache_subdir='embeddings', file_hash=embedding_type_obj.get('file_hash',))
  File "/home/chenqing/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py", line 224, in get_file
    raise Exception(error_msg.format(origin, e.code, e.msg))
Exception: URL fetch failure on https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.simple.vec: 403 -- Forbidden

**Comment by jfilter** [comment]
They seem to have changed the URL for the embeddings. Feel free to send a PR if you have some spare time.

**Comment by chenqing** [comment]
yes , I changed https://github.com/jfilter/text-classification-keras/blob/master/texcla/embeddings.py#L175
to https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/ , it works.

**Comment by chenqing** [comment]
I create a pr.

**Comment by jfilter** [comment]
Thanks! Will look into this soon.

**Comment by jfilter** [comment]
Should work now.
