### ISSUE TITLE
subprocess.CalledProcessError in tokenize.py

### ISSUE THREAD

**Issue by davidlenz** [jfilter/text-classification-keras#8]
Great project Sir! Thanks a lot for maintaining this, i think it is super useful.

I ran into the following error when running the example code from the readme in my newly created environment on a Win10 x64 machine:

```
(kerastext) E:>python texcla_test.py
deep_plots: No display found. Using non-interactive Agg backend.
> Using TensorFlow backend.
> sed: -e expression #1, char 8: unknown option to `s'
> Traceback (most recent call last):
>   File "texcla_test.py", line 15, in <module>
>     experiment.setup_data(X, y, tokenizer, 'data.bin', max_len=100)
>   File "C:\Users\Dlenz\Anaconda3\envs\kerastext\lib\site-packages\texcla\experiment.py", line 128, in setup_data
>     tokenizer.build_vocab(X)
>   File "C:\Users\Dlenz\Anaconda3\envs\kerastext\lib\site-packages\texcla\preprocessing\tokenizer.py", line 194, in build_vocab
>     for token_data in self.token_generator(texts, **kwargs):
>   File "C:\Users\Dlenz\Anaconda3\envs\kerastext\lib\site-packages\texcla\preprocessing\word_tokenizer.py", line 142, in token_generator
>     tokens = fastTextWikiTokenizer.tokenize(text)
>   File "C:\Users\Dlenz\Anaconda3\envs\kerastext\lib\site-packages\texcla\libs\fastTextWikiTokenizer\tokenize.py", line 63, in tokenize
>     return(preproc(s).split())
>   File "C:\Users\Dlenz\Anaconda3\envs\kerastext\lib\site-packages\texcla\libs\fastTextWikiTokenizer\tokenize.py", line 59, in preproc
>     return __digits(__spaces(__normalize_text(s.lower())))
>   File "C:\Users\Dlenz\Anaconda3\envs\kerastext\lib\site-packages\texcla\libs\fastTextWikiTokenizer\tokenize.py", line 38, in __normalize_text
>     ['sed', *commands], input=s.encode()).decode("utf-8")
>   File "C:\Users\Dlenz\Anaconda3\envs\kerastext\lib\subprocess.py", line 336, in check_output
>     **kwargs).stdout
>   File "C:\Users\Dlenz\Anaconda3\envs\kerastext\lib\subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['sed', '-e', "s/’/'/g", '-e', "s/′/'/g", '-e', "s/''/ /g", '-e', "s/'/ ' /g", '-e', 's/“/"/g', '-e', 's/”/"/g', '-e', 's/"/ /g', '-e', 's/\\./ \\. /g', '-e', 's/<br \\/>/ /g', '-e', 's/, / , /g', '-e', 's/(/ ( /g', '-e', 's/)/ ) /g', '-e', 's/\\!/ \\! /g', '-e', 's/\\?/ \\? /g', '-e', 's/\\;/ /g', '-e', 's/\\:/ /g', '-e', 's/-/ - /g', '-e', 's/=/ /g', '-e', 's/=/ /g', '-e', 's/*/ /g', '-e', 's/|/ /g', '-e', 's/«/ /g']' returned non-zero exit status 1.
```

It seems to me like there is an easy fix; i don't see it though.

**Env setup:**
```
conda create -n kerastext python==3.6
activate kerastext
conda install pandas scipy scikit-learn tensorflow-gpu
python -m pip install --upgrade pip
pip install text-classification-keras[full]==0.1.1
```

**keras_test.py :**
```
from texcla import experiment, data
from texcla.models import TokenModelFactory, YoonKimCNN
from texcla.preprocessing import FastTextWikiTokenizer

# input text
X = ['some random text', 'another random text lala', 'peter', ...]

# input labels
y = ['a', 'b', 'a', ...]

# use the special tokenizer used for constructing the embeddings
tokenizer = FastTextWikiTokenizer()

# preprocess data (once)
experiment.setup_data(X, y, tokenizer, 'data.bin', max_len=100)

# load data
ds = data.Dataset.load('data.bin')

# construct base
factory = TokenModelFactory(
    ds.num_classes, ds.tokenizer.token_index, max_tokens=100,
    embedding_type='fasttext.wiki.simple', embedding_dims=300)

# choose a model
word_encoder_model = YoonKimCNN()

# build a model
model = factory.build_model(
    token_encoder_model=word_encoder_model, trainable_embeddings=False)

# use experiment.train as wrapper for Keras.fit()
experiment.train(x=ds.X, y=ds.y, validation_split=0.1, model=model,
    word_encoder_model=word_encoder_model)

```

Any help is greatly appreciated!

**Comment by jfilter** [comment]
Hey, 

this has to do with `FastTextWikiTokenizer` and its dependency on the Unix tool [sed](https://en.wikipedia.org/wiki/Sed). Do you have it installed on your Windows machine? Can you try it with a different variant/installation?

Otherwise, you could start with using another tokenizer. The results may be a little bit worse but it should work.

**Comment by jfilter** [comment]
Feel free to re-open it.
